#!/bin/bash

# install utilities

#cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

binfolder='/home/'${USER}'/bin'
if [ ! -d ${binfolder} ] ; then
	echo 'Creating ~/bin directory in '${binfolder}
	mkdir ${binfolder}
fi

echo 'Linking utilities to the ~/bin directory'
chmod +x MakeLink.sh
./MakeLink.sh

echo 'Creating the manpage. Requires sudo priviledges'
readarray -d : -t arr <<< $(manpath)
manfolder=${arr[1]}
sudo cp ntfy-run.1.gz ${manfolder}/man1/.
